- :error_code: 2
  :error_description: "Unrecognized device."
- :error_code: 3
  :error_description: "'redirect_uri' required."
- :error_code: 4
  :error_description: "'redirect_uri' not authorized by Relying Party"
- :error_code: 5
  :error_description: "'client_id' required."
- :error_code: 6
  :error_description: "'email' is required."
- :error_code: 7
  :error_description: "'email' and 'password' are required."
- :error_code: 8
  :error_description: "The credentials provided are invalid."
- :error_code: 9
  :error_description: "User's email address not yet verified."
- :error_code: 10
  :error_description: "Invalid scope format."
