- :error_code: 1
  :error_description: "Client authentication failed."
- :error_code: 2
  :error_description: "Unrecognized device."
- :error_code: 3
  :error_description: "'redirect_uri' is required."
- :error_code: 4
  :error_description: "'redirect_uri' not authorized by the client."
- :error_code: 5
  :error_description: "'client_id' required."
- :error_code: 6
  :error_description: "'email' is required."
- :error_code: 7
  :error_description: "'email' and 'password' are required."
- :error_code: 8
  :error_description: "The credentials provided are invalid."
- :error_code: 9
  :error_description: "User's email address not yet verified."
- :error_code: 10
  :error_description: "Invalid scope format."
- :error_code: 11
  :error_description: "The client is not authorized to request an authorization code using this method."
- :error_code: 12
  :error_description: "'response_type' required."
- :error_code: 13
  :error_description: "User has no session on device."
- :error_code: 14
  :error_description: "Session expired, user must sign in again."
- :error_code: 15
  :error_description: "Session not found."
- :error_code: 16
  :error_description: "User has signed out, must sign in again."
- :error_code: 17
  :error_description: "End-User authetication is required."
- :error_code: 18
  :error_description: "End-User is required to select a session."
- :error_code: 19
  :error_description: "Use of 'request' parameter is not supported"
- :error_code: 20
  :error_description: "Use of 'request_uri' parameter is not supported"
- :error_code: 21
  :error_description: "Use of 'registration' parameter is not supported"
- :error_code: 22
  :error_description: "We do not support obtaining an authorization code using this method."
- :error_code: 23
  :error_description: "End-Use device has been compromised."
- :error_code: 24
  :error_description: "'client_id' AND 'client_secret' are required for client authentication."
- :error_code: 25
  :error_description: "'code' is required."
- :error_code: 26
  :error_description: "Invalid Authorization Code ('code')."
- :error_code: 27
  :error_description: "The authenticated client is not authorized to use this authorization grant type."
- :error_code: 28
  :error_description: "The authorization grant type is not supported."
- :error_code: 29
  :error_description: "'grant_type' is required."
- :error_code: 30
  :error_description: "'refresh_token' is required."
- :error_code: 31
  :error_description: "Invalid Refresh Token ('refresh_token')."
