- :error_code: 1
  :error_description: "Client authentication failed."
- :error_code: 2
  :error_description: "Unrecognized device."
- :error_code: 3
  :error_description: "'redirect_uri' required."
- :error_code: 4
  :error_description: "'redirect_uri' not authorized by Relying Party"
- :error_code: 5
  :error_description: "'client_id' required."
- :error_code: 6
  :error_description: "'email' is required."
- :error_code: 7
  :error_description: "'email' and 'password' are required."
- :error_code: 8
  :error_description: "The credentials provided are invalid."
- :error_code: 9
  :error_description: "User's email address not yet verified."
- :error_code: 10
  :error_description: "Invalid scope format."
- :error_code: 11
  :error_description: "The client is not authorized to request an authorization code using this method."
- :error_code: 12
  :error_description: "'response_type' required."
- :error_code: 13
  :error_description: "User has no session on device."
- :error_code: 14
  :error_description: "Session expired, user must sign in again."
