development: &non_production_settings
  :iss: https://accounts.licentia.digital
  :sign_in_service: http://localhost:4200
  :account_management: http://localhost:4300
  :expiration_time: 3600
  :scopes:
    - openid
    - listDevices

test:
  <<: *non_production_settings
  :scopes:
    - openid
    - email
    - listDevices

production:
  <<: *non_production_settings
  :sign_in_service: https://accounts.licentia.digital/SignInService
  :account_management: https://accounts.licentia.digital/AccountManagement
