development: &non_production_settings
  :iss: https://accounts.zetios.com.br
  :expiration_time: 3600

test:
  <<: *non_production_settings

production:
  :iss: https://accounts.zetios.com.br
  :expiration_time: 3600
