development: &non_production_settings
  :iss: http://localhost:3000
  :sign_in_service: http://localhost:4200
  :account_management: http://localhost:4300
  :expiration_time: 3600
  :scopes:
    - openid
    - listDevices
    - listRelyingParties
    - updateProfile

test:
  <<: *non_production_settings
  :scopes:
    - openid
    - email
    - listDevices
    - listRelyingParties
    - updateProfile

production:
  <<: *non_production_settings
  :sign_in_service: https://accounts.zetios.com.br/SignInService
  :account_management: https://accounts.zetios.com.br/AccountManagement
